<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-APM.Container-DA2C8612-32AB-43CE-BF03-7CDB88F82EEC</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="WolverineFx" Version="5.14.0" />
        <PackageReference Include="WolverineFx.RabbitMQ" Version="5.14.0" />

                <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core.Kernel\Core.Kernel.csproj"/>
        <ProjectReference Include="..\Library.Skopeo\Library.Skopeo.csproj"/>
    </ItemGroup>
</Project>
