<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Collector.Huggingface-7d0110ed-6756-4ec2-a07f-5a44632b91ae</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.1.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Collector.Kernel\Collector.Kernel.csproj" />
      <ProjectReference Include="..\Core.Kernel\Core.Kernel.csproj" />
    </ItemGroup>
</Project>
